site_name: DUCKView
site_description: "Taking the duck ouf of SANView"
repo_url: "https://github.com/b-skwad/duckview"
edit_uri: "blob/master/docs/"
repo_name: "b-skwad/duckview"

theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.instant
    - navigation.tracking

plugins:
  - search
  - autorefs
  - mkdocstrings

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tilde

nav:
  - Home: index.md
  - Press release/FAQ: prfaq.md
  - Installation of the SCDE:
      - Prerequisites: cdf/prerequisites.md
      - Visual Studio Code: cdf/vscode.md
      - Docker Desktop: cdf/docker-desktop.md
      - Install Ubuntu on Windows: cdf/ubuntu.md
      - SSH on Ubuntu/GitHub: cdf/ssh-on-ubuntu.md
      - GPG on Ubuntu/GitHub: cdf/gpg-on-ubuntu.md
      - Git on Ubuntu: cdf/gpg-and-git.md
  - Using the Repository:
      - Cloning the Repository: usage/cloning-the-repo.md
      - Opening the Project: usage/opening-the-project.md
  - Glossary:
      - Working With GitHub: glossary/working-with-github.md
      - Using GitFlow: glossary/gitflow.md
      - Markdown Cheat-sheet: glossary/mark-down.md