name: Release and Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Pre-merge checks for Master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: Configure Poetry
        run: $HOME/.poetry/bin/poetry config virtualenvs.create false

      - name: Install Python Packages
        run: $HOME/.poetry/bin/poetry install

      - name: Get Latest
        run: git pull

      - name: Build the Docs site
        run: mkdocs gh-deploy